Auth backend
moneybunney/MoneyBunney pull request #4
Opened 2019-03-12 14:26 UTC by MantasGra

2019-03-12 14:38 UTC, Martynas-S commented
Pataisyk importus i relative

2019-03-12 16:08 UTC, Andrius-B requested changes
Solid work, bet  reik perdaryt į mongoose 😄 
[dar vienas link į tuos pačius doc'us](https://mongoosejs.com/docs/#)

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/user.entity.ts
> +export class UserEntity extends BaseEntity {
Ummm Mantai, mes buvom nusprendę naudot `mongoose` kaip ORM, tai šito failo čia neturėtų būt, o turėtum visur naudot schemą iš failo `backend/src/modules/user/user.shemas.ts`

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/schemas/user.shemas.ts
> +export const UserSchema = new mangoose.Schema({
Failas tikriausiai turėtų vadintis `user.schema.ts`

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/user.service.ts
> +import { MongoRepository, Column, ObjectID } from 'typeorm';
Čia irgi reikėtų naudot mongoose (esmė lygiai ta pati):

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/user.service.ts
> +    constructor(@InjectRepository(UserEntity) private readonly userRepository : MongoRepository<UserEntity>) {}
Čia reikėtų pasiimt mongoose modulį su `const User = mongoose.model('User', UserSchema);`
_aš čia trumpų pavyzdžių duosiu kaip pakeist typeorm į mongoose, [daugiau skaityk docs'uose](https://mongoosejs.com/docs/)_

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/user.service.ts
> +        const users: UserEntity[] = await this.userRepository.find();
čia turėtų būt 
```typescript
const usersPromise = User.find().exec() // suranda visus
[..etc..]
```

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/interfaces/IUserService.ts
> +import { CreateUserDto } from '../dto/create-user.dto';
Failo pavadinimas tikriausiai turėtų būt `user.service.ts`

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/dto/create-user.dto.ts
> +import {ApiModelProperty} from '@nestjs/swagger';
Failas tikriausiai turėtų vadintis `user.dto.ts` ir reik mąstyt apie tokio perkėlimą į `/models` (šalia `backend` ir `frontend`)

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/user.controller.ts
> +        console.log('Get to /user | getAllUsers');
Būtų pretty cool naudot [nest utils logginimui](https://docs.nestjs.com/techniques/logger), o ne console.log

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/dto/create-user.dto.ts
> +export class CreateUserDto {
Klasė taip pat tikriausiai turėtų vadintis `UserDTO` - siūlau daudot `DTO` didžiasias, nes vis dėlto čia akronimas

2019-03-12 16:08 UTC, Andrius-B commented on backend/src/modules/user/interfaces/user.interface.ts
> +export interface User extends Document {
šiuo metu šita klasė nei kart nepanaudota (tikiuosi, kad neilgai taip bus 😺 )

2019-03-12 16:11 UTC, Andrius-B commented on backend/src/modules/user/user.controller.ts
> +        console.log('Get to /user | getAllUsers');
Čia docsai prastai paaiškina kaip jį naudot, tai [yra SO klausimas](https://stackoverflow.com/questions/52650895/how-to-use-nestjs-logging-service)

2019-03-12 16:25 UTC, Martynas-S requested changes
Perziek situos dalykus, bet siaip viskas ciki

2019-03-12 16:25 UTC, Martynas-S commented on backend/src/common/error/AppError.ts
> +                    httpStatus: HttpStatus.UNPROCESSABLE_ENTITY,
Cia turetu but 409 manau

2019-03-12 16:25 UTC, Martynas-S commented on backend/src/common/error/AppError.ts
> +            case AppErrorTypeEnum.NO_USERS_IN_DB:
`NO_USERS_IN_DB` net neturetu buti error state'as, tai tiesiog turetu grazinti tuscia visu useriu objekta `{}` ir statusa `200`, nes requestas gerai praejo :D

2019-03-12 16:25 UTC, Martynas-S commented on backend/src/modules/user/interfaces/user.interface.ts
> +    readonly username: string;
Cia ir visur kitur, reiketu pragreppint projekta zodzio `username` ir pakeisti i `email` :D

2019-03-12 16:25 UTC, Martynas-S commented on backend/src/modules/user/user.controller.ts
> +    @ApiResponse({ status: 404, description: 'No Users found.'})
Cia tas pats, kad `No Users found` nera error state API'juje

2019-03-12 16:25 UTC, Martynas-S commented on backend/src/modules/user/user.controller.ts
> +    @ApiResponse({ status: 422, description: 'User already exists.'})
https://httpstatuses.com/409

2019-03-12 16:25 UTC, Martynas-S commented on backend/src/modules/user/user.service.ts
> +        const u: UserEntity = await this.userRepository.findOne({username: user.username});
Nice variable name XD

2019-03-12 16:25 UTC, Martynas-S commented on backend/src/modules/user/user.controller.spec.ts
> +    expect(controller).toBeDefined();
Tai tu pakurei situs testus, kurie failina :DD. Okei as tuoj sutvarkysiu

2019-03-12 16:33 UTC, Martynas-S commented on backend/src/modules/user/user.service.spec.ts
> +      providers: [UserService],
Man atrodo tu blogai kazkaip exportuoji ir UserService ir UserController ir del to testai failina. Reikia pasibandyt lokaliai

2019-03-12 18:14 UTC, Martynas-S commented
Ahoi, dar reikia kad kai sekmingai priregistruoji useri tai irgi settintu cookie

2019-03-12 22:50 UTC, MantasGra commented
Lygtais viską, ką paimnėjote, vyručiai, sutvarkiau dabar. 😅

2019-03-13 07:40 UTC, Martynas-S approved these changes
Viskas dabar good tik reikia dar du dalykus padaryt:

- Imergint development ir issprest merge conflicta
- Istrint neveikiancius testus

Ir tuomet galim mergint i development

2019-03-13 11:38 UTC, Martynas-S commented
Dar galvoju gal reiketu padaryti validacija emailo, kai kuriamas accountas, kad grazintu errora jei dalykas kuri submittini nera panasus i emaila :D 
http://emailregex.com/

2019-03-13 11:40 UTC, Andrius-B approved these changes

2019-03-13 12:20 UTC, Martynas-S commented
Ai, tiesa, dar vienas dalykas: pries merginant reikia pravaziuoti su tslintu fixinant dalykus ir galu gale su prettier suformatuot viska

2019-03-15 20:56 UTC, merged