Docker fix
moneybunney/MoneyBunney pull request #46
Opened 2019-04-28 20:43 UTC by Andrius-B

For deployment, `docker-compose build && docker-compose up` should do it, but now every host/port is globally configured in the top-level .env

2019-04-29 08:28 UTC, Andrius-B commented
Aš atsakau tas codacity manęs asmeniškai nemėgsta 😢

2019-04-29 08:33 UTC, Martynas-S commented
> Aš atsakau tas codacity manęs asmeniškai nemėgsta

Jis gerus dalykus siulo

2019-04-29 09:02 UTC, Andrius-B commented
> > Aš atsakau tas codacity manęs asmeniškai nemėgsta
> 
> Jis gerus dalykus siulo

Nu jo šitas šiaip visai nieko, bet ...

2019-04-30 10:11 UTC, Martynas-S requested changes
This breaks the backend locally, which cannot use the .env variables because you are not using the `ConfigService`

2019-05-01 13:40 UTC, Martynas-S approved these changes
Sutaisyk builda ir merge conflictus ir bombs away :1st_place_medal:

2019-05-01 18:38 UTC, Martynas-S commented
Tough luck, dar nesutaisei. Gali lokaliai patikrint testus pries pushindamas

2019-05-01 19:15 UTC, merged

2019-05-03 12:43 UTC, Martynas-S commented
Jei kada nors domins to service race condition issprendimas tai vo:
https://docs.docker.com/compose/startup-order/