Add account validation to transaction form
moneybunney/MoneyBunney pull request #52
Opened 2019-04-29 17:41 UTC by Andrius-B

The transaction form now waits for account load, and validates if a correct account is selected
This closes #49

2019-05-01 17:11 UTC, Martynas-S requested changes

2019-05-01 17:11 UTC, Martynas-S commented on backend/.env.example
> -DB_PORT=27017
??? Jei istrinsi sita backas nebeveiks

2019-05-01 17:11 UTC, Martynas-S commented on frontend/src/Views/Checkout/Checkout.tsx
> +      const fetchedAccounts = await getAccounts();
Galetum naudot `useAccounts()` hooka

2019-05-06 18:45 UTC, Martynas-S commented
Ar 5f684375fdcb1b921d83ca3e66a7ff5a77a06ae8 sena `development` versija imergino? :DDD

2019-05-07 05:20 UTC, Andrius-B commented
whoopsy daisy

2019-05-07 06:05 UTC, Martynas-S commented on frontend/src/Views/Checkout/Checkout.tsx
> +        setTransaction(createEmptyTransaction({ account: accounts[0].id }));
O kas jeigu internetas yra labai letas, accountus pafetchint trunka 2 sekundes ir tu jau buni pradejes rasyti savo transaction ir bum, pareina accountas ir tavo transaction WIP yra iswipinamas?

2019-05-07 06:30 UTC, Andrius-B commented on frontend/src/Views/Checkout/Checkout.tsx
> +        setTransaction(createEmptyTransaction({ account: accounts[0].id }));
pats kaltas bus tas useris :)

2019-05-07 06:31 UTC, Martynas-S commented on frontend/src/Views/Checkout/Checkout.tsx
> +        setTransaction(createEmptyTransaction({ account: accounts[0].id }));
Ah, I see, sita problema matyt nera issprendziama programically, dar irankiai nera tiek pazenge kad handlintu toki extreme case

2019-05-07 06:36 UTC, Andrius-B commented on frontend/src/Views/Checkout/Checkout.tsx
> +        setTransaction(createEmptyTransaction({ account: accounts[0].id }));
Kaip tik, priešingai - 5G jau ne už kalnų, nebereik net galvot apie tokias dinozauriškas problemas

2019-05-07 06:38 UTC, Martynas-S commented on frontend/src/Views/Checkout/Checkout.tsx
> +        setTransaction(createEmptyTransaction({ account: accounts[0].id }));
: )

2019-05-07 10:26 UTC, Martynas-S approved these changes

2019-05-07 10:39 UTC, merged